GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

### Malformated id
GET http://localhost:3001/api/notes/11

### correct id
GET http://localhost:3001/api/notes/61b5d7ec0bd04a0708a712e2

### PUT
PUT http://localhost:3001/api/notes/61b5d7ec0bd04a0708a712e2
Content-Type: application/json

{
  "content": "HTML is Easy",
  "date": "2021-12-12T11:07:24.003Z",
  "important": true,
  "id": "61b5d7ec0bd04a0708a712e2"
}